version: '3.1'

services:

  mongo:
    container_name: mongo-database
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 7017:27017
